import { Color, GameBoard } from '../../helpers/helpersBack';
export const gameBoard: GameBoard = {
    map: [
        { y: 0, x: 4, chequers: [], start: Color.red },
        { y: 1, x: 4, chequers: [], start: -1 },
        { y: 2, x: 4, chequers: [], start: -1 },
        { y: 3, x: 4, chequers: [], start: -1 },
        { y: 4, x: 4, chequers: [], start: -1 },
        { y: 4, x: 3, chequers: [], start: -1 },
        { y: 4, x: 2, chequers: [], start: -1 },
        { y: 4, x: 1, chequers: [], start: -1 },
        { y: 4, x: 0, chequers: [], start: -1 },
        { y: 5, x: 0, chequers: [], start: -1 },
        { y: 6, x: 0, chequers: [], start: Color.blue },
        { y: 6, x: 1, chequers: [], start: -1 },
        { y: 6, x: 2, chequers: [], start: -1 },
        { y: 6, x: 3, chequers: [], start: -1 },
        { y: 6, x: 4, chequers: [], start: -1 },
        { y: 7, x: 4, chequers: [], start: -1 },
        { y: 8, x: 4, chequers: [], start: -1 },
        { y: 9, x: 4, chequers: [], start: -1 },
        { y: 10, x: 4, chequers: [], start: -1 },
        { y: 10, x: 5, chequers: [], start: -1 },
        { y: 10, x: 6, chequers: [], start: Color.green },
        { y: 9, x: 6, chequers: [], start: -1 },
        { y: 8, x: 6, chequers: [], start: -1 },
        { y: 7, x: 6, chequers: [], start: -1 },
        { y: 6, x: 6, chequers: [], start: -1 },
        { y: 6, x: 7, chequers: [], start: -1 },
        { y: 6, x: 8, chequers: [], start: -1 },
        { y: 6, x: 9, chequers: [], start: -1 },
        { y: 6, x: 10, chequers: [], start: -1 },
        { y: 5, x: 10, chequers: [], start: -1 },
        { y: 4, x: 10, chequers: [], start: Color.yellow },
        { y: 4, x: 9, chequers: [], start: -1 },
        { y: 4, x: 8, chequers: [], start: -1 },
        { y: 4, x: 7, chequers: [], start: -1 },
        { y: 4, x: 6, chequers: [], start: -1 },
        { y: 3, x: 6, chequers: [], start: -1 },
        { y: 2, x: 6, chequers: [], start: -1 },
        { y: 1, x: 6, chequers: [], start: -1 },
        { y: 0, x: 6, chequers: [], start: -1 },
        { y: 0, x: 5, chequers: [], start: -1 },
    ],
    // @ts-ignore
    bases: {
        [Color.red]: [
            { x: 1, y: 1, chequer: -1 },
            { x: 1, y: 2, chequer: -1 },
            { x: 2, y: 2, chequer: -1 },
            { x: 2, y: 1, chequer: -1 },
        ],
        [Color.blue]: [
            { x: 8, y: 1, chequer: -1 },
            { x: 9, y: 1, chequer: -1 },
            { x: 9, y: 2, chequer: -1 },
            { x: 8, y: 2, chequer: -1 },
        ],
        [Color.green]: [
            { x: 8, y: 8, chequer: -1 },
            { x: 9, y: 8, chequer: -1 },
            { x: 9, y: 9, chequer: -1 },
            { x: 8, y: 9, chequer: -1 },
        ],
        [Color.yellow]: [
            { x: 1, y: 8, chequer: -1 },
            { x: 2, y: 8, chequer: -1 },
            { x: 2, y: 9, chequer: -1 },
            { x: 1, y: 9, chequer: -1 },
        ],
    },
    // @ts-ignore
    homes: {
        [Color.red]: [
            { x: 5, y: 1, chequer: -1 },
            { x: 5, y: 2, chequer: -1 },
            { x: 5, y: 3, chequer: -1 },
            { x: 5, y: 4, chequer: -1 },
        ],
        [Color.blue]: [
            { x: 1, y: 5, chequer: -1 },
            { x: 2, y: 5, chequer: -1 },
            { x: 3, y: 5, chequer: -1 },
            { x: 4, y: 5, chequer: -1 },
        ],
        [Color.green]: [
            { x: 5, y: 9, chequer: -1 },
            { x: 5, y: 8, chequer: -1 },
            { x: 5, y: 7, chequer: -1 },
            { x: 5, y: 6, chequer: -1 },
        ],
        [Color.yellow]: [
            { x: 9, y: 5, chequer: -1 },
            { x: 8, y: 5, chequer: -1 },
            { x: 7, y: 5, chequer: -1 },
            { x: 6, y: 5, chequer: -1 },
        ],
    }
}